{
  "formatVersion": "1.1",
  "component": {
    "group": "de.dennisthegamer",
    "module": "hudlib-ui",
    "version": "1.0.7+mc1.21-1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.dennisthegamer",
          "module": "hudlib-core",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "hudlib-ui-1.0.7+mc1.21-1.21.8.jar",
          "url": "hudlib-ui-1.0.7+mc1.21-1.21.8.jar",
          "size": 162782,
          "sha512": "699b400d342e7132228088f5e7b44087b1604292ebbda9bba4eb0c25e96bf85417f5fc55fe0bd8b2a215047b0cd9ba5fae8c896c2e9d0a34a7be37cc4f9077e8",
          "sha256": "9c28ca41ea1d65eff1c0e983e97deb48250e81ca2d27f61be065691baaad4749",
          "sha1": "7501b30ce60be9f7aca7fdfea957c96a281ed35b",
          "md5": "b988101014d7521003501c598ee827df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.dennisthegamer",
          "module": "hudlib-core",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "hudlib-ui-1.0.7+mc1.21-1.21.8.jar",
          "url": "hudlib-ui-1.0.7+mc1.21-1.21.8.jar",
          "size": 162782,
          "sha512": "699b400d342e7132228088f5e7b44087b1604292ebbda9bba4eb0c25e96bf85417f5fc55fe0bd8b2a215047b0cd9ba5fae8c896c2e9d0a34a7be37cc4f9077e8",
          "sha256": "9c28ca41ea1d65eff1c0e983e97deb48250e81ca2d27f61be065691baaad4749",
          "sha1": "7501b30ce60be9f7aca7fdfea957c96a281ed35b",
          "md5": "b988101014d7521003501c598ee827df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hudlib-ui-1.0.7+mc1.21-1.21.8-sources.jar",
          "url": "hudlib-ui-1.0.7+mc1.21-1.21.8-sources.jar",
          "size": 160746,
          "sha512": "28b3014b5229fa23bc7b3ac501f2657e6b1423a311a3c2604fc9b3340b41cfb50ee80a2aa3a23f48dd3f6904e696f49e446b00811a324e61c622cf8dfd29a1f8",
          "sha256": "d12545c2b2cd64d1d5cf4f9f359596903d1e42ad172f4f0cd16e1ba1262f04a4",
          "sha1": "b14b853b31826765f998221159e896e8a52d4335",
          "md5": "e3f6160868781345ac78be09fc7c92d7"
        }
      ]
    }
  ]
}
