{
  "formatVersion": "1.1",
  "component": {
    "group": "de.dennisthegamer",
    "module": "hudlib-ui-neoforge",
    "version": "1.0.5+mc1.21.9-1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.dennisthegamer",
          "module": "hudlib-core",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "hudlib-ui-neoforge-1.0.5+mc1.21.9-1.21.11.jar",
          "url": "hudlib-ui-neoforge-1.0.5+mc1.21.9-1.21.11.jar",
          "size": 162739,
          "sha512": "f2535b432bdf773db832af6c02ffd75ac87994dc5706c479a4d1398ca33b93ebcc87e340bfa7c100ddb0591f1413bf9b56c9d99990fc67c53e82061611750144",
          "sha256": "2f87fb84012f83948b73cf18a999fc96a9584bec9c246d0245db07d0d0579018",
          "sha1": "333cf9b2fe0b734ee412c6a46d086ffc99cac6da",
          "md5": "a908bd1326abc4efe1f05495b861d0dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.dennisthegamer",
          "module": "hudlib-core",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "hudlib-ui-neoforge-1.0.5+mc1.21.9-1.21.11.jar",
          "url": "hudlib-ui-neoforge-1.0.5+mc1.21.9-1.21.11.jar",
          "size": 162739,
          "sha512": "f2535b432bdf773db832af6c02ffd75ac87994dc5706c479a4d1398ca33b93ebcc87e340bfa7c100ddb0591f1413bf9b56c9d99990fc67c53e82061611750144",
          "sha256": "2f87fb84012f83948b73cf18a999fc96a9584bec9c246d0245db07d0d0579018",
          "sha1": "333cf9b2fe0b734ee412c6a46d086ffc99cac6da",
          "md5": "a908bd1326abc4efe1f05495b861d0dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hudlib-ui-neoforge-1.0.5+mc1.21.9-1.21.11-sources.jar",
          "url": "hudlib-ui-neoforge-1.0.5+mc1.21.9-1.21.11-sources.jar",
          "size": 160347,
          "sha512": "ca46b4a4a1638e33c9a9cae5c9b9a5df1292d826bdd034246281bb9bdce22f44fffe004ca68b6c09b0a6fd33852cabb6d4c0c39c2de080ff678f95719615e1ae",
          "sha256": "552387688461b03ba25c344a47c985af3068b833aaf53aa8b7c9f8e8515ff346",
          "sha1": "e70f2525d122da10130ee864c71e036894dbf0d3",
          "md5": "c9416a0e9b8291270558a8f0ba9b7c73"
        }
      ]
    }
  ]
}
