{
  "formatVersion": "1.1",
  "component": {
    "group": "de.dennisthegamer",
    "module": "hudlib-ui-neoforge",
    "version": "1.0.5+mc1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.dennisthegamer",
          "module": "hudlib-core",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "hudlib-ui-neoforge-1.0.5+mc1.21.5.jar",
          "url": "hudlib-ui-neoforge-1.0.5+mc1.21.5.jar",
          "size": 162500,
          "sha512": "20c2e64a2c5f939be10eaee3345405ba6327c195033842834361f97cab054296ce8da2dc81d746df92f2f0d8ea4cb6b1bef8493b5d7fdbeb95abca88f0694cea",
          "sha256": "611ced7d27e241c9e7c621b86769fc473a2bd51db01cabd7f00d497c2691a616",
          "sha1": "af4f6af50dce015f6f1db6e4279f8899abd78374",
          "md5": "0ce24a10da5817051b57eb0bd1cb9312"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.dennisthegamer",
          "module": "hudlib-core",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "hudlib-ui-neoforge-1.0.5+mc1.21.5.jar",
          "url": "hudlib-ui-neoforge-1.0.5+mc1.21.5.jar",
          "size": 162500,
          "sha512": "20c2e64a2c5f939be10eaee3345405ba6327c195033842834361f97cab054296ce8da2dc81d746df92f2f0d8ea4cb6b1bef8493b5d7fdbeb95abca88f0694cea",
          "sha256": "611ced7d27e241c9e7c621b86769fc473a2bd51db01cabd7f00d497c2691a616",
          "sha1": "af4f6af50dce015f6f1db6e4279f8899abd78374",
          "md5": "0ce24a10da5817051b57eb0bd1cb9312"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hudlib-ui-neoforge-1.0.5+mc1.21.5-sources.jar",
          "url": "hudlib-ui-neoforge-1.0.5+mc1.21.5-sources.jar",
          "size": 159932,
          "sha512": "8a7300f3cb1572a0de4a9459adaa8404a7d441d7168620ee7f1a05ed605e4b9dbc3b57bcc867442cb1446e419bf4d31aa697762d44ca693d5cbe677107c1dacd",
          "sha256": "17f5a292abf9f51f1f10dc716565503009553b31c314455514681224941989fe",
          "sha1": "d1e16fc6793f329a56758a42a01b93936247922e",
          "md5": "3e9c73f235aa4dec95bdabea967bdd41"
        }
      ]
    }
  ]
}
