{
  "formatVersion": "1.1",
  "component": {
    "group": "de.dennisthegamer",
    "module": "hudlib-core",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hudlib-core-1.0.6.jar",
          "url": "hudlib-core-1.0.6.jar",
          "size": 149703,
          "sha512": "f060c714413c1c5a61c4e505c6271deaf7eefbd3012101b604a9f587a8104844929f08e35ef278cbb26b7d17acdba2735bb406ebdbce81296edc2bdc940c4319",
          "sha256": "8d1b54932e86239d6b9d5140a45b2501c86f4b408ae7c3e805cb65a988b460ef",
          "sha1": "167f3623b36c769e31d20696020288175e1ff25b",
          "md5": "dfde9180d43d26fb0a8368e92461faa6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hudlib-core-1.0.6.jar",
          "url": "hudlib-core-1.0.6.jar",
          "size": 149703,
          "sha512": "f060c714413c1c5a61c4e505c6271deaf7eefbd3012101b604a9f587a8104844929f08e35ef278cbb26b7d17acdba2735bb406ebdbce81296edc2bdc940c4319",
          "sha256": "8d1b54932e86239d6b9d5140a45b2501c86f4b408ae7c3e805cb65a988b460ef",
          "sha1": "167f3623b36c769e31d20696020288175e1ff25b",
          "md5": "dfde9180d43d26fb0a8368e92461faa6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hudlib-core-1.0.6-sources.jar",
          "url": "hudlib-core-1.0.6-sources.jar",
          "size": 145584,
          "sha512": "2b898f42e9d4291b114e5392f1466eb9d20b92937ef7d275b005b793d09e7e997ff58f81829b1530561b9d8024d2554ca0e10f07ea481bb1b185644f31339fce",
          "sha256": "5c2e84ee7d3814475dc41afb77eada329f023a6c3e152562970283fb2a9dde3a",
          "sha1": "90f9a3ab86aa8ced9aceef0ed88319e39a86c683",
          "md5": "b528ebe96bb802b4a6942986168bbd14"
        }
      ]
    }
  ]
}
